Documentation:
  Enabled: false

Rails:
  Enabled: true
AllCops:
  DisabledByDefault: true
  UseCache: true
  DisplayCopNames: true
  TargetRailsVersion: 5.2

  Include:
    - 'test.rb'

Style/FrozenStringLiteralComment:
  Description: 'Add the frozen string literal directive to the top of the file.'
  Enabled: true
